In [190]:
import pandas as pd

# Define columns and their respective data types
dtype_mapping = {
    'Age_Category': str, 'Gender_of_Child': str, 'Childs_Education_Level': str,
    'Religion': str, 'BMI_category': str, 'Tribe_of_Child': str, 'orphanhood': str,
    'Socio_Economic_Status': str, 'Support_Program': str, 'Child_Takes_ART': str,
    'Premature_Birth': str, 'Born_with_HIV': str, 'Stress': str, 'Worst_HIV_Stage': str,
    'CD4_category': str, 'Viralload_Category': str, 'Telomere_Lenth_Difference': float, 'telomere_length_change': str,
    'stin2vntr_': str, 'httlpr1_polymorphism': str, 'HTTLPRrs35531': str,
    'rs35531_polymorphism': str, 'Rs10482605_polymorphism': str,
    'Rs1360780_polymorphism': str, 'rs1386494_polymorphism': str,
    'rs1843809_polymorphism': str, 'rs34517220_polymorphism': str, 'GroupCategory': str,
    'IMDs': str, 'Age': float, 'Baseline_telomere_length': float, 'Telomere_length_12Months': float
}

# Read the CSV file with specified data types
IMD_IMD = pd.read_csv("IMD Incidence CSV Data.csv", dtype=dtype_mapping, encoding='latin1')

# Display the first few rows of the DataFrame
IMD_IMD.head(5)

,Age,Age_Category,Gender_of_Child,Childs_Education_Level,Religion,BMI_category,Tribe_of_Child,orphanhood,Socio_Economic_Status,Support_Program,...,httlpr1_polymorphism,HTTLPRrs35531,rs35531_polymorphism,Rs10482605_polymorphism,Rs1360780_polymorphism,rs1386494_polymorphism,rs1843809_polymorphism,rs34517220_polymorphism,GroupCategory,IMDs
0,4.999316,Nine to Twelve,Female,Pre-primary,Christians,Underweight,Muganda,Both parents alive,low socio-economic status,No,...,LS,LA/SA,A:A,G:A,C:T,G:G,T:T,A:A,controls,No
1,5.004791,Nine to Twelve,Female,Pre-primary,Christians,Underweight,Muganda,Both parents alive,low socio-economic status,No,...,LS,LA/SA,A:A,A:A,C:T,G:A,G:G,G:A,controls,Yes
2,5.007529,Nine to Twelve,Female,Pre-primary,Christians,Underweight,Muganda,Single parent alive,low socio-economic status,No,...,LL,LA/LG,A:G,A:A,T:T,A:A,G:G,A:A,controls,Yes
3,5.023956,Five to Eight,Female,Pre-primary,Christians,Underweight,Muganda,Both parents alive,low socio-economic status,No,...,LL,LA/LG,A:G,A:A,T:T,G:G,T:T,A:A,controls,Yes
4,5.026694,Thirteen to Seventeen Years,Female,Pre-primary,Christians,Underweight,Non-Munganda but Ugandan,Both parents alive,high socioecnomic status,No,...,LL,LA/LA,A:A,A:A,C:T,G:A,T:G,A:A,controls,Yes

In [191]:

# Display the first few rows of the DataFrame
IMD_IMD.isnull().sum().sum()

849

In [192]:
import pandas as pd

# Assuming you have a DataFrame named 'IMD_Copy' and the variables of interest are 'stin2vntr_', 'telomere_length_change', and 'Age_Category'
variables_of_interest = ['stin2vntr_', 'telomere_length_change', 'Age_Category']

# Iterate over each variable
for variable in variables_of_interest:
    # Calculate frequency of each unique value for the current variable
    frequency_table = IMD_IMD[variable].value_counts().reset_index()
    frequency_table.columns = ['Categories', 'Freq']
    
    # Calculate percentage
    total_count = frequency_table['Freq'].sum()
    frequency_table['Percentage'] = (frequency_table['Freq'] / total_count) * 100
    
    # Add a column for the variable name
    frequency_table['Var'] = variable
    
    # Reorder columns
    frequency_table = frequency_table[['Var', 'Categories', 'Freq', 'Percentage']]
    
    # Print frequency table for the current variable
    print(frequency_table)
    print()

          Var Categories  Freq  Percentage
0  stin2vntr_      12/12   177   55.835962
1  stin2vntr_      10/12   112   35.331230
2  stin2vntr_      10/10    28    8.832808

                      Var Categories  Freq  Percentage
0  telomere_length_change  Decreased   181   77.350427
1  telomere_length_change  Increased    53   22.649573

            Var                   Categories  Freq  Percentage
0  Age_Category                Five to Eight   134   36.413043
1  Age_Category               Nine to Twelve   129   35.054348
2  Age_Category  Thirteen to Seventeen Years   105   28.532609

In [193]:
# Display the first few rows of the DataFrame
IMD_IMD.isnull().sum().sum()

849

In [194]:
import pandas as pd
from sklearn.impute import KNNImputer

# Separate features and target variable
IMD_2 = IMD_IMD.copy()
# Identify numerical and categorical (object) columns
numerical_cols = IMD_2.select_dtypes(include=['float64', 'int64']).columns
categorical_cols = IMD_2.select_dtypes(include=['object']).columns

# Impute missing values for numerical columns
numerical_imputer = SimpleImputer(strategy='mean')
numerical_imputed = pd.DataFrame(numerical_imputer.fit_transform(IMD_2[numerical_cols]), columns=numerical_cols)

# Impute missing values for categorical columns
categorical_imputer = SimpleImputer(strategy='most_frequent')
categorical_imputed = pd.DataFrame(categorical_imputer.fit_transform(IMD_2[categorical_cols]), columns=categorical_cols)

# Combine imputed numerical and categorical columns
IMD_2_imputed = pd.concat([numerical_imputed, categorical_imputed], axis=1)

In [195]:
# Display the first few rows of the DataFrame
IMD_2_imputed.isnull().sum().sum()

0

In [196]:
IMD_2_imputed.dtypes

Age                          float64
Baseline_telomere_length     float64
Telomere_length_12Months     float64
Telomere_Lenth_Difference    float64
Age_Category                  object
Gender_of_Child               object
Childs_Education_Level        object
Religion                      object
BMI_category                  object
Tribe_of_Child                object
orphanhood                    object
Socio_Economic_Status         object
Support_Program               object
Child_Takes_ART               object
Premature_Birth               object
Born_with_HIV                 object
Stress                        object
Worst_HIV_Stage               object
CD4_category                  object
Viralload_Category            object
telomere_length_change        object
stin2vntr_                    object
httlpr1_polymorphism          object
HTTLPRrs35531                 object
rs35531_polymorphism          object
Rs10482605_polymorphism       object
Rs1360780_polymorphism        object
rs1386494_polymorphism        object
rs1843809_polymorphism        object
rs34517220_polymorphism       object
GroupCategory                 object
IMDs                          object
dtype: object

In [197]:
IMD_2_imputed.to_stata("Trial_imputed2_data.dta", version=118)

In [198]:
import pandas as pd

# Assuming you have a DataFrame named 'IMD_Copy' and the variables of interest are 'stin2vntr_', 'telomere_length_change', and 'Age_Category'
variables_of_interest = ['stin2vntr_', 'telomere_length_change', 'Age_Category']

# Iterate over each variable
for variable in variables_of_interest:
    # Calculate frequency of each unique value for the current variable
    frequency_table = IMD_2_imputed[variable].value_counts().reset_index()
    frequency_table.columns = ['Categories', 'Freq']
    
    # Calculate percentage
    total_count = frequency_table['Freq'].sum()
    frequency_table['Percentage'] = (frequency_table['Freq'] / total_count) * 100
    
    # Add a column for the variable name
    frequency_table['Var'] = variable
    
    # Reorder columns
    frequency_table = frequency_table[['Var', 'Categories', 'Freq', 'Percentage']]
    
    # Print frequency table for the current variable
    print(frequency_table)
    print()

          Var Categories  Freq  Percentage
0  stin2vntr_      12/12   228   61.956522
1  stin2vntr_      10/12   112   30.434783
2  stin2vntr_      10/10    28    7.608696

                      Var Categories  Freq  Percentage
0  telomere_length_change  Decreased   315   85.597826
1  telomere_length_change  Increased    53   14.402174

            Var                   Categories  Freq  Percentage
0  Age_Category                Five to Eight   134   36.413043
1  Age_Category               Nine to Twelve   129   35.054348
2  Age_Category  Thirteen to Seventeen Years   105   28.532609

In [199]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Normalizer, OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# Separate features and target variable
IMD_Copy = IMD_2_imputed.copy()

# Label encode the IMD_Copy variable if it's categorical
for column in IMD_Copy.columns:
    if IMD_Copy[column].dtype == 'object' or IMD_Copy[column].dtype.name == 'category':
        label_encoder = LabelEncoder()
        IMD_Copy[column] = label_encoder.fit_transform(IMD_Copy[column])
IMD_Copy.head(5)

,Age,Baseline_telomere_length,Telomere_length_12Months,Telomere_Lenth_Difference,Age_Category,Gender_of_Child,Childs_Education_Level,Religion,BMI_category,Tribe_of_Child,...,httlpr1_polymorphism,HTTLPRrs35531,rs35531_polymorphism,Rs10482605_polymorphism,Rs1360780_polymorphism,rs1386494_polymorphism,rs1843809_polymorphism,rs34517220_polymorphism,GroupCategory,IMDs
0,4.999316,1.251031,0.884187,0.234441,1,0,1,0,3,0,...,1,2,0,1,1,2,2,0,0,0
1,5.004791,1.682923,0.914863,0.768060,1,0,1,0,3,0,...,1,2,0,0,1,1,0,1,0,1
2,5.007529,0.019943,0.884187,0.234441,1,0,1,0,3,0,...,0,1,1,0,2,0,0,0,0,1
3,5.023956,0.985791,0.854123,0.131668,0,0,1,0,3,0,...,0,1,1,0,2,2,2,0,0,1
4,5.026694,1.227321,1.376915,-0.149594,2,0,1,0,3,1,...,0,0,0,0,1,1,1,0,0,1

In [200]:
import pandas as pd

# Assuming you have a DataFrame named 'IMD_Copy' and the variables of interest are 'stin2vntr_', 'telomere_length_change', and 'Age_Category'
variables_of_interest = ['stin2vntr_', 'telomere_length_change', 'Age_Category']

# Iterate over each variable
for variable in variables_of_interest:
    # Calculate frequency of each unique value for the current variable
    frequency_table = IMD_Copy[variable].value_counts().reset_index()
    frequency_table.columns = ['Categories', 'Freq']
    
    # Calculate percentage
    total_count = frequency_table['Freq'].sum()
    frequency_table['Percentage'] = (frequency_table['Freq'] / total_count) * 100
    
    # Add a column for the variable name
    frequency_table['Var'] = variable
    
    # Reorder columns
    frequency_table = frequency_table[['Var', 'Categories', 'Freq', 'Percentage']]
    
    # Print frequency table for the current variable
    print(frequency_table)
    print()

          Var  Categories  Freq  Percentage
0  stin2vntr_           2   228   61.956522
1  stin2vntr_           1   112   30.434783
2  stin2vntr_           0    28    7.608696

                      Var  Categories  Freq  Percentage
0  telomere_length_change           0   315   85.597826
1  telomere_length_change           1    53   14.402174

            Var  Categories  Freq  Percentage
0  Age_Category           0   134   36.413043
1  Age_Category           1   129   35.054348
2  Age_Category           2   105   28.532609

In [201]:
IMD_Copy.dtypes

Age                          float64
Baseline_telomere_length     float64
Telomere_length_12Months     float64
Telomere_Lenth_Difference    float64
Age_Category                   int32
Gender_of_Child                int32
Childs_Education_Level         int32
Religion                       int32
BMI_category                   int32
Tribe_of_Child                 int32
orphanhood                     int32
Socio_Economic_Status          int32
Support_Program                int32
Child_Takes_ART                int32
Premature_Birth                int32
Born_with_HIV                  int32
Stress                         int32
Worst_HIV_Stage                int32
CD4_category                   int32
Viralload_Category             int32
telomere_length_change         int32
stin2vntr_                     int32
httlpr1_polymorphism           int32
HTTLPRrs35531                  int32
rs35531_polymorphism           int32
Rs10482605_polymorphism        int32
Rs1360780_polymorphism         int32
rs1386494_polymorphism         int32
rs1843809_polymorphism         int32
rs34517220_polymorphism        int32
GroupCategory                  int32
IMDs                           int32
dtype: object

In [202]:
# Separate features and target variable
IMD_2 = IMD_IMD.copy()

X_full = IMD_2 .drop('IMDs', axis=1)
y_full = IMD_2 ['IMDs']

# Identify categorical variables
categorical_cols = X_full.select_dtypes(include=['object']).columns.tolist()

# Apply label encoding to categorical variables
label_encoder = LabelEncoder()
X_encoded = X_full.copy()
for col in categorical_cols:
    X_encoded[col] = label_encoder.fit_transform(X_full[col])

In [ ]:
# Separate features and target variable
IMD_2 = IMD_IMD.copy()

X_full = IMD_2 .drop('IMDs', axis=1)
y_full = IMD_2 ['IMDs']

# Identify categorical variables
categorical_cols = X_full.select_dtypes(include=['object']).columns.tolist()

# Apply label encoding to categorical variables
label_encoder = LabelEncoder()
X_encoded = X_full.copy()
for col in categorical_cols:
    X_encoded[col] = label_encoder.fit_transform(X_full[col])

# Impute missing values
imputer = KNNImputer(n_neighbors=5)
imputed_data = imputer.fit_transform(X_encoded)
imputed_dataframe = pd.DataFrame(imputed_data, columns=X_encoded.columns)

imputed_dataframe.head(-10)